export const SITE_CONFIG = {
  name: "Semaphore 2K26",
  shortName: "Semaphore 2026",
  title: "Semaphore 2K26 | National Level IT Fest | NMAMIT Nitte",
  description:
    "Official website of Semaphore 2K26: AquaSaga — Premier National Level Technical Fest organized by the Department of MCA, NMAM Institute of Technology (NMAMIT), Nitte. Featuring 10 flagship coding competitions, web design, gaming, IT manager, start-up pitching, IT quiz, and ₹1.5L+ prize pool.",
  url: "https://www.semaphore2k26.in",
  themeColor: "#00dbe9",
  backgroundColor: "#020714",
  locale: "en_IN",
  ogImage: "/techy_underwater_bg.png",
  logo: "/logo.png",
  festLogo: "/aquasaga_logo.png",
  eventDates: {
    start: "2026-09-17T09:00:00+05:30",
    end: "2026-09-18T18:00:00+05:30",
    formatted: "17-18 September 2026",
  },
  venue: {
    name: "NMAM Institute of Technology (NMAMIT)",
    alternateName: "Nitte Mahalinga Adyanthaya Memorial Institute of Technology",
    department: "Department of Master of Computer Applications (MCA)",
    streetAddress: "Nitte, Karkala Taluk",
    addressLocality: "Karkala",
    addressRegion: "Karnataka",
    postalCode: "574110",
    addressCountry: "IN",
    geo: {
      latitude: "13.1827",
      longitude: "74.9348",
    },
    mapUrl: "https://maps.google.com/?q=NMAMIT+Nitte+Karkala",
  },
  contact: {
    email: "semaphore2026@gmail.com",
    departmentEmail: "semaphore@nitte.edu.in",
    staffCoordinator: {
      name: "Dr. Roshan D Suvaris",
      role: "Faculty Coordinator",
      phone: "+919663484343",
    },
    studentCoordinator: {
      name: "Vansh Shetty",
      role: "Student Coordinator",
      phone: "+919019720766",
    },
  },
  social: {
    instagram: "https://www.instagram.com/semaphore.26",
    samcaInstagram: "https://www.instagram.com/samca_nitte_mca",
    youtube: "https://www.youtube.com/@SAMCANMAMIT",
    mcaWebsite: "https://nitte.edu.in/nmamit/department-mca.php",
  },
  keywords: [
    "Semaphore 2K26",
    "Semaphore 2026",
    "Semaphore technical fest",
    "Semaphore MCA NMAMIT",
    "NMAMIT Nitte technical fest",
    "AquaSaga Semaphore",
    "National Level IT Fest 2026",
    "MCA Fest Karnataka",
    "Coding competition 2026",
    "Web design hackathon NMAMIT",
    "IT Quiz competition Nitte",
    "IT Manager competition",
    "Gaming competition NMAMIT",
    "StartUp Pitch contest",
    "College technical fest Karnataka",
    "Student coding events Udupi",
    "Mangalore college technical fest",
  ],
};
